### ISSUE TITLE
Carpet Bomber Code bitte.

### ISSUE THREAD

**Issue by Schroedinger100PCT** [PlaceDE-Official/zinnsoldat#1]
Das bookmarklet funktioniert recht gut bisher. (Ehre)
Könntet ihr den Code für Carpet Bomber teilen? 
Das würde dezentrale Operation ermöglichen und selbigen entlasten. 
Für alle Nutzer die sehr viele Accounts besitzen währe es auch vorteilhaft CB lokal zu betreiben.

**Comment by fgardt** [comment]
Tampermonkey gibts auch schon hier: https://github.com/PlaceDE-Official/zinnsoldat/raw/main/output/placebot.user.js

**Comment by fgardt** [comment]
aufgrund der architektur machen weitere Carpetbomber instanzen keinen Sinn, wird es also nicht geben.

**Comment by Schroedinger100PCT** [comment]
Wer hätte Bock an einem Dezentralen Carpetbomber zu arbeiten?  Wir brauchen eine halt neue Strategie für die Tokenvergabe. Eventuell immer c.a. 100 accouts um die selbe pixelmap konkurieren lassen, oder das ganze in Zonen pro Server einteilen und einen zentralen server anpingen um Erreichbarkeit der Dezentalen Carpetbomber zu beweisen?

**Comment by fgardt** [comment]
also Lastprobleme wird es keine geben, wir können den Carpetbomber problemlos skalieren. Nur die Architektur an sich erlaubt es nicht das dezentral und public von 3ten laufen zu lassen.
