### ISSUE TITLE
C&C Verhalten erwünscht?

### ISSUE THREAD

**Issue by DooMMasteR** [PlaceDE-Official/zinnsoldat#22]
Mein client sendet:
```js
{
    type: "RequestJobs", 
    tokens: ["Wololo"]
}
```
und bekommt als Antwort immer
```js
{
    type: "Jobs", 
    jobs: {
        Wololo: [null, "Invalid"]
    }
}
```

Ist das so erwünscht? Ich habe noch nie ein Kommando bekommen :-)

**Comment by Skillkiller** [comment]
Ja das Verhalten ist erwünscht. Das kommt wenn keine Aufträge aktuell verfügbar sind. Wenn alle Pixel so wie geplant sind weil zum Beispiel mehr Bots als überwachte Pixel online sind, sind keine Aufträge verfügbar. Der Bot versucht es dann 20 Sekunden später erneut und irgendwann ändert sich auch die Antwort wenn wieder Aufträge verfügbar sind.

**Comment by fgardt** [comment]
Exakt!
