### ISSUE TITLE
Cooldown nicht vollkommen ausreizen

### ISSUE THREAD

**Issue by etillxd** [PlaceDE-Official/zinnsoldat#30]
Wäre es evtl. Sinnvoll (optional) zusätzlich zum normalen cooldown teilweise eine  zufällige, geringe Anzahl von Sekunden zu warten, um das Bannrisiko für Bots die mehrere Stunden/Tage am stück laufen zu minimieren?

**Comment by Bloeckchengrafik** [comment]
Ist eigentlich implementiert...
https://github.com/PlaceDE-Official/zinnsoldat/blob/main/index.js#L460

**Comment by Pandafishie** [comment]
> Ist eigentlich implementiert... https://github.com/PlaceDE-Official/zinnsoldat/blob/main/index.js#L460

An der stelle wird überprüft, ob deine Computerzeit mit der Serverzeit (sehr grob) übereinstimmt. Das hat nichts mit einem zusätzlichen cooldown zu tun, nur weil da "time" steht.

Des weiteren sollte man bei solchen Zitaten nicht auf den last commit verweisen sondern good practice nach einen Verweis mit dem jeweiligen letzten Commit, da sich der Code jederzeit ändern kann und damit auch Zeilen verutschen.
Hier wäre das also:
https://github.com/PlaceDE-Official/zinnsoldat/blob/23e2c35f8d03f8ddde717b11b020333cc69ddd8c/index.js#L460

Ist aber trotzdem immer noch nicht das, wonach der OP des Issues gefragt hat.

**Comment by Pandafishie** [comment]
Kommentar diesbezüglich von B0rbor4d auf Discord (discord.gg/placede).
Siehe hier: https://discord.com/channels/297765871122907136/1132576483643248712/1132928207809687553

> Wir haben bereits verschleierungsmechanismen implementiert. Auf Details wird vor Ende des Events aus Sicherheitsgründen nicht näher Eingegangen, aber dinge wie random Timer sind bereits implementiert. Des weiteren ist uns bis dato kein nachweisbarer Fall bekannt der eindeutig auf die Nutzung des Zinnsoldaten zurückzuführen ist.

**Comment by Bloeckchengrafik** [comment]
Die referenzierte Stelle ist aktuell hier:

https://github.com/PlaceDE-Official/zinnsoldat/blob/23e2c35f8d03f8ddde717b11b020333cc69ddd8c/index.js#L523

Mir ist bewusst, dass der code in aktuell L460 zur Verhinderung von #29 da ist; ich habe kurz nach dem Merge der dazugehörenden PR mit Play_it über die Umsetzung dieses Features in der inoffiziellen Node/Docker-Version im Discord diskutiert.
