### ISSUE TITLE
Vorschlag: Meldung, welcher Pixel wann zuletzt gesetzt wurde dauerhaft

### ISSUE THREAD

**Issue by Janmm14** [PlaceDE-Official/zinnsoldat#8]
Dauerhaft halt

**Comment by fasti001** [comment]
In der F12-Konsole stehen die Koordinaten.

![image](https://github.com/PlaceDE-Official/zinnsoldat/assets/118815078/0a13ba79-edb5-454c-9cbe-eead4f5e9a44)

<br> <br>

Einfach F12 drücken, auf Konsole gehen und oben Fehler und Warnungen deaktivieren.

![image](https://github.com/PlaceDE-Official/zinnsoldat/assets/118815078/520f7071-f2cd-4ba0-bc88-dc6d1fec2d82)
